// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
    datasource: {
    // כאן אנחנו אומרים לפריזמה מאיפה לקחת את הכתובת
    url: process.env.DATABASE_URL,
  },
});
// if there is problem try to change the code for this:
// import { defineConfig } from "@prisma/config"; // שים לב ל- @

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   datasource: {
//     url: process.env.DATABASE_URL,
//   },
// });
// 